version: '3'
services:
  salt-master:
    build: ./salt-master
    container_name: provisoner
    ports:
      - "8000:8000"
      - "4505:4505"
      - "4506:4506"
    volumes:
      - ./salt-master/config:/etc/salt/master.d
      - ./salt-master/ssh:/root/.ssh
      - ./salt-master/salt:/srv/salt
      - ./salt-master/pillar:/srv/pillar
      - ./salt-master/pki:/etc/salt/pki/master
      - ./salt-master/autosign_grains:/etc/salt/autosign_grains
    environment:
      - SALT_SHARED_SECRET=${SALT_SHARED_SECRET:not-so-secret}
